project_id = "wpjxsgxxhogzkkuznyke"

[functions.debug-inbound]
verify_jwt = false

[functions.download-media]
verify_jwt = false

[functions.send-wa-message]
verify_jwt = true

[functions.send-bulk-messages]
verify_jwt = true

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.sync-whatsapp-templates]
verify_jwt = true

[functions.clickup-create-task]
verify_jwt = false

[functions.clickup-update-task]
verify_jwt = false

[functions.clickup-update-task-status]
verify_jwt = false

[functions.clickup-webhook]
verify_jwt = false

[functions.import-contacts]
verify_jwt = true

[functions.delete-message]
verify_jwt = true

[functions.restore-message]
verify_jwt = true

[functions.n8n-trigger]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.ai-communicator]
verify_jwt = true

[functions.send-wa-media]
verify_jwt = true

[functions.upload-media]
verify_jwt = true

[functions.n8n-send-message]
verify_jwt = false

[functions.ai-virtual-agent]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-list-voices]
verify_jwt = true

[functions.firecrawl-scrape-knowledge]
verify_jwt = true
